-- task_4.sql

SELECT 
  COLUMN_NAME, 
  DATA_TYPE, 
  CHARACTER_MAXIMUM_LENGTH, 
  NUMERIC_PRECISION, 
  NUMERIC_SCALE, 
  COLUMN_DEFAULT, 
  IS_NULLABLE, 
  COLUMN_KEY, 
  EXTRA
FROM 
  INFORMATION_SCHEMA.COLUMNS
WHERE 
  TABLE_NAME = 'books';
